### ISSUE TITLE
Setup basic package structure

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#1]
- [x] Create a package with PkgTemplates and push to https://github.com/QuantEcon/SimpleDifferentialOperators.jl 
- [x] Get documentation generating as well.  The issue is we need to be able to do math examples.
- [x] https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/utils/diffusionoperators.jl  will go into the package in one form or another
- [x] Find the old tests we had for those functions and put those in as our baseline tests.

**Comment by arnavs** [comment]
Done at 6a47b3a.
