### ISSUE TITLE
Add in a simple benchmarking file, not running in travis 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#10]
After benchmarked, see if this should be a `0` or a `0.0`: https://github.com/QuantEcon/SimpleDifferentialOperators.jl/blob/master/src/operators.jl#L8

Can also check if a specialized reflecting one (i.e. not just a proxy to the rboin) is significantly faster.

**Comment by arnavs** [comment]
Done with the last commit. We check for type stability in our tests, and the specialized method thing isn't relevant anymore because of the refactor.
