### ISSUE TITLE
Based on the algebra, revisit implementation and basis

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#101]
After #100 is done, revisit the formulas.  In particular, never check types within a single function if at all possible, better map of code to algebra and use multiple-dispatch.

**Comment by jlperla** [comment]
When we do this, since everything will be written in terms of banded matrices, etc. we can use `BandedMatrices.jl` for both the unit tests and sometimes the implementation.

**Comment by chiyahn** [comment]
Use `spdiag(-1 => foo, 2 => bar)` instead as it's not clear how we can stack up the banded matrix `L` and the boundary condition matrix `B` together.
