### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/SimpleDifferentialOperators.jl#115]
In order for the latest release to be merged on METADATA, we need to make sure that CI for the package passes. 

@chiyahn Since you designed the new interface, do you want to handle this? If you're busy though, I can take a look.

**Comment by arnavs** [comment]
Here is the PR: https://github.com/JuliaLang/METADATA.jl/pull/22622

**Comment by chiyahn** [comment]
Oh, I thought the recent CI within the package must have sufficed. You might want to handle this for me.

**Comment by arnavs** [comment]
Ok, sounds good. I think we may just need to manually edit the TOML to say v0.4.0 (this is an annoying new requirement.) Will close and re-open if need be.
