### ISSUE TITLE
Merge changes from PR then tag new release 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#135]
- [x] Merge #133 after review
- [ ] tag a new version so the stable points to the help with the docs
- [ ] make sure to rebuild the notebooks and pdfs for both the tagged version and dev (and test it works with stable
- [x] add link to stable derivation on front readme https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/generated/discretized-differential-operator-derivation.pdf   i.e. fix #136

**Comment by chiyahn** [comment]
Closing as the new version is now out: https://github.com/QuantEcon/SimpleDifferentialOperators.jl/releases/tag/v0.4.2
