### ISSUE TITLE
Incorrect statement of ODE for the jump diffusion process

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#173]
See https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-jump-diffusion-1 and the equation.

- [x] It shouldn't say lambda `lambda L_n v(x)` but rather be `\lambda (v(x-0.01) - v(x)` in the equation.  The L_n only enters when we discretzie. (Resolved by f9e88e0)    
- [x] Move the description there as well that says "corresponding operator" to below, where we actually use it in the discretization. (Resolved by f9e88e0)
- [ ] If you did something similar in the notebook, then fix it as well.  Speaking of which, I can't see the notebook in https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/notebooks/ that you did with the stopping problem?  Did you forget to merge and add to this list?
- [x] See comment on https://github.com/QuantEcon/SimpleDifferentialOperators.jl/commit/f9e88e06819baab35be8057886f59bf981368896

**Comment by chiyahn** [comment]
I'll make a fix once soon once I finish writing up the math for discrete-continuous state stuff. The notebook is still in a PR (I'll merge it after I make a fix)
