### ISSUE TITLE
Expand out the table of contents in the help

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#178]
In the table of contents of the Usage section in https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/ is there any way for us to have it list out the different experiments so it is easier to jump to them?  e.g. something like
```
- Installation
- Usage
  - Solving HJBE with constant drifts
  - Solving HJBE with absorbing barrier conditions
   ...
- Notebooks
- API
```
If in order to do that, you need to kick things up a level to have the TOC pick it up, then maybe try changing the structure to something like
``````
# ﻿[SimpleDifferentialOperators.jl](https://github.com/QuantEcon/SimpleDifferentialOperators.jl/)
# Installation and Derivations

To install, run
```julia
] add SimpleDifferentialOperators
```
Note that this requires Julia 1.1 or later.

See the documentation for the [detailed derivations](generated/discretized-differential-operator-derivation.pdf).

## Solving HJBE with constant drifts

Consider solving for `v` from the following equation by the Hamilton-Jacobi-Bellman equation (HJBE):
``````

**Comment by jlperla** [comment]
@arnavs , are you able to take a look at the table of contents structure when you get a chance?  I think you setup the original Documenter structure.

**Comment by arnavs** [comment]
No problem. Yeah, I set it up- I think this is definitely possible by tweaking a setting for TOC depth. Will take a look.

**Comment by arnavs** [comment]
Alright @jlperla take a look at the `dev` docs (you'll have to go to the dropdown in the main docs.) Sorry for delay; took some slight detours to patch up other issues here and there with things like Registrator. 

I did the grouping in the "canonical" way, e.g. the one at the bottom [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/guide.md).

**Comment by arnavs** [comment]
Closing per slack.
