### ISSUE TITLE
Add support for "Interior" of diffusionoperators

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#18]
The idea would be to return the discretionary of the operator with no boundaries.  Something like:
```
using SimpleDifferentialOperators
μ = -0.1 # constant negative drift
σ = 0.1
N = 10
grid = range(0.0, 1.0, length = N) # uniform grid on [0.0, 1.0]

L_1_minus, L_1_plus, L_2, x_bar = diffusionoperators(grid, NoBoundary())
```
The size of the resulting `L_1_minus`, `L_1_plus` etc.  should be `N` by `(N+2)` for all of them.
I only put a single `NoBoundary()` since it wouldn't make sense to do it one-sided, but if that messes up the dispatch then you can have it twice.

A few other things
- [x] This should return back a sparse matrix rather than the tridiagonal since it is no longer square.  Later we can play around with banded matrices  (Resolved by 883f796)
- [x] Implement for both regular and irregular  (Resolved by 883f796)
- [x] I put in the `x_bar` since we should return back the list of nodes *including* the ghost nodes.  This is of length `N+2`, where the inside of it is just the `grid` above.  We should have this everywhere.  (Resolved by 883f796)
- [x] This should be the default, if no boundaries are given with `diffusionoperators`  i.e. something like
```
diffusionoperators(x) = diffusionoperators(x, NoBoundary())
``` 
 (Resolved by a01edf5)
- [x] All help for this should use the default `diffusionoperators(x)` to show how to use it.  People don't really need to know about the internal `NoBoundary` (Resolved by a01edf5)
- [x] We should have the example solve the same problem with the reflecting boundary and the no boundary at the same time. (Resolved by 0af7fb6) That is comparing,
```
μ = -0.1 # constant negative drift
σ = 0.1
N = 10
x = range(0.0, 1.0, length = N)
L_1_minus, L_1_plus, L_2, x_bar = diffusionoperators(x, Reflecting(), Reflecting())
A = μ*L_1_minus + σ^2 / 2 * L_2 
f(x) = x^2
v = A \ f.(x) # Solve the value function
```
To something like 
```
μ = -0.1 # constant negative drift
σ = 0.1
N = 10
x = range(0.0, 1.0, length = N)
L_1_minus, L_1_plus, L_2, x_bar = diffusionoperators(x)
L = μ*L_1_minus + σ^2 / 2 * L_2 
B = [- 1 1 zeros(N);
       zeros(N) 1 -1]
A = [L; B]
f(x) = x^2
v_bar = A \ f.(x_bar) # solve the value function including the ghost nodes
v = v_bar(2:end-1) # extract on the interior
```

**Comment by jlperla** [comment]
From #27 I am not sure if these stencils should include a superscript of E to say they are defined on the exterior including ghost nodes... Lets be consistent and update PDERoadmap if needed.

Also, see if you think an overline instead of the E would be more consistent?

**Comment by jlperla** [comment]
I am rethinking this interface a bit... But let's get solid regression tests for all of this stuff first, and then we can rearrange.

In the meantime, I don't think there is sufficient benefit to merge in the "no boundary" case into the main interface. 

But the question of a superscript E vs a bar is very important for all of this.

**Comment by chiyahn** [comment]
+1 for a bar -- that would make it more consistent with extended grids for ghost nodes (that are overline/underlined) suggested in #27

**Comment by jlperla** [comment]
Done. Can you submit a PR for it to the PDERoadmap as well which makes the change?

**Comment by chiyahn** [comment]
Sounds good.

**Comment by chiyahn** [comment]
@jlperla I am not sure if the system in the example is solvable when we use reflecting barriers. Take, for instance, N = 3 -- this results in the following generator
```julia
julia> A
3×3 Tridiagonal{Float64,Array{Float64,1}}:
 -0.02   0.02    ⋅
  0.22  -0.24   0.02
   ⋅     0.22  -0.22
```
whose rank is clearly two. 

Also, `x_bar` for operators without boundary conditions should be
```julia
x_bar = [x[1]; x; x[end]]
```
rather than the one with actual ghost nodes, i.e.,
```julia
deltas = diff(x)
[(x - deltas[1]); x; (x + deltas[end])]
````
It is not difficult to see that the resulting `A` will lead to the same system, which is, not of full rank as above.

**Comment by jlperla** [comment]
No, the definition of x_bar is independent of the application of the boundary conditions, although perhaps it has to do with the order of the operators. (i.e. only 1 point on each side for a 2nd order operator, though for first order ones we can just put both sides on it anyways).
I think you need to read the PDERoadmap a little more carefullly on that one to make sure you are being consistent with it.

**Comment by jlperla** [comment]
you need to substract the r * I or else the rank is always one less than the total.
i.e.
```L_2 = diffusionoperators([1,2,3], Reflecting(), Reflecting()).L_2
(I * 0.05 - L_2) \ [1, 2, 3]```
solves `0.05 v(z) = z + D_zz v(z)`

**Comment by chiyahn** [comment]
> No, the definition of x_bar is independent of the application of the boundary conditions, although perhaps it has to do with the order of the operators. (i.e. only 1 point on each side for a 2nd order operator, though for first order ones we can just put both sides on it anyways).

It is true. However, in the example provided, that was not the case. The last two rows of `f.(x_bar)` should correspond to the boundary conditions instead -- hence it must be rather `[f.(x); 0.; 0.]`

Here's a complete example

```julia
# setup 
f(x) = x^2
μ = -0.1 # constant negative drift
σ = 0.1
N = 3
x = range(0.0, 1.0, length = N)

# operators with reflecting boundary conditions
L_1_minus, L_1_plus, L_2, x_bar = diffusionoperators(x, Reflecting(), Reflecting())
A = μ*L_1_minus + σ^2 / 2 * L_2 
v = (I * 0.05 - A) \ f.(x) # Solve the value function

# operators without boundary conditions, adding extra two rows for boundary conditions
L_1_minus, L_1_plus, L_2, x_bar = diffusionoperators(x)
L = μ*L_1_minus + σ^2 / 2 * L_2 
B = transpose([[-1; 1; zeros(N)] [zeros(N); -1; 1]])
A = [([zeros(N) Diagonal(ones(N,N)) zeros(N)] * 0.05 - L); B]
v_bar = A \ [f.(x); 0.0; 0.0] # solve the value function including the boundary conditions
v = v_bar[2:end-1] # Extract on the interior
```

**Comment by jlperla** [comment]
I don't think this is correct

**Comment by jlperla** [comment]
Sorry, I think you are misunderstanding things here. The xbar is the xbar. Going `f.(xbar) ` is meaninglessness since that function isn't defined on the exterior ghost nodes.

The [0,0] you are stacking is (potentially affine) part of the boundary condition. Please go through the PDERoadmap to make sure you have the notation down

**Comment by chiyahn** [comment]
Reclosing as discussed in Slack -- just as a note: I am not using `f.(x_bar)` at all -- I am stacking up the boundary conditions in the last two rows of `A` in the updated example I posted at https://github.com/QuantEcon/SimpleDifferentialOperators.jl/issues/18#issuecomment-466581969
