### ISSUE TITLE
Add x_bar to the returned values from all of the diffusion operators

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#19]
In the creation of #18, it became clear that we really want the grid, but with the ghost nodes.
In the PDERoadmap notation, this is `x_bar` .

- [x] Regular grid ghost nodes are just using the appropriate `\Delta` back and forward on both sides of the `x` (Resolved by 883f796)
- [x] Irregular grid ghost nodes should align with the assumption used in the stencil.  I believe that is `Delta_0^- = Delta_0^+` etc.  (Resolved by 883f796)

**Comment by chiyahn** [comment]
Resolved by 883f796.
