### ISSUE TITLE
Absorbing barrier where the "bottom" is not necessarily the 0'th node.

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#190]
Not going to support reflecting or mixed off of the bottom.
- [x] Math with a homogenous absorbing barrier at a higher grid location.  By default it is at the `0`.   
  - For example, say that it was at the 2nd node instead of the 0th node,
  - I think that we just need to show the additional equations in the gaussian elimination.
  - Would have a few columns of zeros, etc.
- [ ] Document a simple example for the homogenous case
- [x] Affine boundary condition math just to check
  - Only support a "constant" value for the non-homogeneous absorbing barrier.

**Comment by chiyahn** [comment]
Need to use affineboundary condition functions, math will be updated accordingly soon
