### ISSUE TITLE
Implementation of the absorbing (not at the boundary)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#191]
After #190 

Basically it is an absorbing where we pass in the node location of the boundary.
Right now it is 
```
struct Absorbing <: HomogeneousBoundaryCondition end
```
Perhaps better if it is
```
struct Absorbing <: HomogeneousBoundaryCondition
   loc::Int
end
```
with the default as `loc = 0` in the constructor, which is our current code.

--

- [x] Implementation
- [x] Unit tests
- [x] Package jldocs
- [x] Example in main docs (Resolved in 66a3947)

**Comment by chiyahn** [comment]
Implementation complete in #198 (with affine boundary), will merge once a PR for #190 is merged (need some fix for math)
