### ISSUE TITLE
Implement the compilation of the docs and the notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#194]
- [x] Remember to cleanup the documenter .`jl` file for building docs to make it more standard.
  - Check environment variable that travis might set
   - Make sure that runs on a local machine for testing (e.g. if the tag enivornment variabler isn't set, it doesn't break).
- [x] Do you know which tag your on when running documenter to generate a link?
- [x] Change the links on the README to point at the right things.  i.e. on the front page is https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/generated/discretized-differential-operator-derivation.pdf    Change this to something else, make it the "dev" or "master" one
- [x] Change the docs themselves to point at the releases for the notebooks and the pdf
  - Work for both the master and the tagged versions if possible.
- [x] After the whole thing is setup, we need to change the links to the latest docs in the PTW repository/tex file.

**Comment by arnavs** [comment]
Did what's required here, and updated the links from PTW.
