### ISSUE TITLE
Consider a reorganization of the interface

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#2]
Right now the interface is
```
 (x, L_1_minus, L_1_plus, L_2) =  rescaled_diffusionoperators(x, ξ)
```

The "rescaled" part of that is not relevant.  That should be removed for sure.  the `ξ` should default to `0` which means it is simply a dirichlet boundary condition?

I think this should probably return a named tuple instead, as well, with the names `grid, L_1_minus, L_1_plus, and L_2`

Maybe just call it
```
 (x, L_1_minus, L_1_plus, L_2) =  diffusionoperators(x, ξ = 0)
```

**Comment by jlperla** [comment]
Alternatively, it may make sense to describe these as a particular type of `robin` boundary conditions in the name, where it is dirichlet at both ends by default (i.e. when `ξ = 0`)
So perhaps 
```
robin_diffusionoperators(x, ξ)
```
and then define a proxy.
```
reflecting_diffusionoperators(x) = robin_diffusionoperators(x, 0)
```
The reason to use "reflecting" is that this would probably be used exclusively by economists, who are more interested in the stochastic processes.

**Comment by arnavs** [comment]
Done. I also chose to drop the return of the `grid`, because we pass it as an argument to the function? But if we want to put it back, that can be done easily.

**Comment by jlperla** [comment]
`grid` was a vector, not a range.

**Comment by arnavs** [comment]
That's true, it helps in the uniform grid case. Will add it back in.

**Comment by jlperla** [comment]
Actually, might as well remove it.  They can turn their range into a vector if they want to.

**Comment by arnavs** [comment]
OK I’ll revert my change.
