### ISSUE TITLE
Implement state varying drift with DiffEqOperators 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#206]
See https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/examples/#Solving-HJBE-with-state-dependent-drifts-1

Follow the patterns of #204 

Note, we don't think these will work until some bugs are fixed, but they are intended as a starting point for the tests.

**Comment by jlperla** [comment]
cc: @ajozefiak for following what Pooya is up to.

**Comment by PooyaFa** [comment]
I've already done this in the #204
