### ISSUE TITLE
Implement HJBE with absorbing barrier with DiffEqOperators

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#207]
Following the #204 pattern
@ajozefiak

**Comment by jlperla** [comment]
https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/examples/#Solving-HJBE-with-absorbing-barrier-conditions-1

**Comment by PooyaFa** [comment]
It's done in https://github.com/QuantEcon/SimpleDifferentialOperators.jl/pull/205 . However, I couldn't find an equivalent use of `Laffine` in DEO. @ajozefiak it would be great if you suggest a better way.

**Comment by PooyaFa** [comment]
Except for `Laffine` which for this example is only for the first element of `\pi_star`, I think the test and samples are ready to work on.
