### ISSUE TITLE
Solve the KFE with and without drifts with Diffeqoperators

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#208]
@ajozefiak Follow the pattern of #204 

See https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/examples/#Finding-stationary-distribution-from-the-Kolmogorov-forward-equation-(KFE)-1

**Comment by PooyaFa** [comment]
Done by the last commit in PR: https://github.com/QuantEcon/SimpleDifferentialOperators.jl/pull/205/commits/3e6d2636ec9dce46d6b2459ec7da67c7113dba80
