### ISSUE TITLE
Images in README

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/SimpleDifferentialOperators.jl#210]
cc @chiyahn @jlperla 

It looks like the images (e.g. of equations) are linked from something called `quicklatex.com` (not familiar with this site.) But I can't see any of the images when I open the README (regardless of device, caching, etc.) Maybe an account has run out, or they only persist the images for so long. 

Perhaps the images could be re-generated and stored locally, and then displayed from e.g. `docs/assets` or something like that?

Example of what I see: 

<img width="949" alt="Screen Shot 2019-12-09 at 2 45 06 PM" src="https://user-images.githubusercontent.com/5009477/70479574-81982280-1a92-11ea-93a0-fdab8950dff0.png">

**Comment by jlperla** [comment]
@chiyahn  Can you crush this out?  I think the math formulas are in the main repo.  Use https://alexanderrodin.com/github-latex-markdown/ as the trick to put it in github (basically just copy the latex in there and paste the markdown back)
