### ISSUE TITLE
Use the DiffEqOperators stencil 

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/SimpleDifferentialOperators.jl#24]
Migrating @jlperla’s issue from PTW:

It would be interesting to see if https://github.com/JuliaDiffEq/PDERoadmap/pull/34 works for the core stencil for solving the simple model.  Start with the stationary test.

The key here is that the operators become composable ways to create matrix-free operators.   Ultimately, that could help us out as it generates an efficient kernel for calculating the RHS of the system of ODEs rather than doing a bunch of matrix multiplications with temporaries, as we currently do.

For this, I think we need to use the regular grid, but that may be fine for a quick check.  I believe that this basically means
- [ ] Try to get the code in that PR working and figure out how do do some basic calls with it.
- [ ] https://github.com/MSeeker1340/PDERoadmap/blob/first-target-option-2/operator_examples/first_target.jl should be added into our package so we can use those types directly (i.e., it is not in the DiffEqOperators package yet).
- [ ] Then instead of using https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/diffusionoperators.jl  in https://github.com/jlperla/PerlaTonettiWaugh.jl/blob/master/src/simple/stationary.jl#L28-L29  we would compose the operator.
- [ ] For the composition, it may be that the `L_1_minus` and `L_2` end up just using the new types in that PR.  You can test it out.  The `v = L \ π_tilde.(z)` might need an extra step to solve the system if it doesn't work directly.  In particular, you might need to use a matrix-free solver.

**Comment by jlperla** [comment]
This will wait for the diffeqoperators update
