### ISSUE TITLE
Add basis matrix generator and use it for reflecting barrier conditions

### ISSUE THREAD

**Issue by chiyahn** [QuantEcon/SimpleDifferentialOperators.jl#25]
This will remove a number of code duplication needed for #18 
- [x] Add basis matrix generator (Resolved by d7eff34)
- [x] Use them for current reflecting barrier operator generator (`_diffusionoperators(x, BC1::Reflecting, BC2::Reflecting)`) (Resolved by d7eff34)

**Comment by chiyahn** [comment]
Resolved by d7eff34

**Comment by chiyahn** [comment]
Update: applied basis matrix generator for mixed bc operator generator as well at 48e0451. One drawback is that now even for a uniform range case `diff(x)` has to be used rather than `step(x)`, but clearly the gain (clarity in code) outweighs the drawback, which is essentially an extremely small amout of computational cost.

**Comment by jlperla** [comment]
Don't do anything crazy with calculations until AFTER you have the comprehensive regression tests. I would rather stick with the forumulas we know work until we can be confident that errors would be found
