### ISSUE TITLE
Solving dynamics with time dependent payoff functions

### ISSUE THREAD

**Issue by chiyahn** [QuantEcon/SimpleDifferentialOperators.jl#33]

**Comment by jlperla** [comment]
Was thinking along the lines of one of these: https://github.com/econtoolkit/continuous_time_methods/blob/master/matlab/tests/discretize_time_varying_univariate_diffusion_test.m

But with the ODE solver rather than the homegrown discretization.

**Comment by chiyahn** [comment]
First version created at https://github.com/ubcecon/computing_and_datascience/blob/355c0306b2685a018b5452caf225ee1528f0128a/continuous_time_methods/tutorials/hjb-with-time-dependent-payoff.md
