### ISSUE TITLE
Example and tests combining the forward/backword first differences

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#34]
Solve the simple bellman with a drift of both signs in the range, showing how to combine that L_1^+ and L_1^- operators.  I would prefer if this was setup with an example `μ(x) = ...` function which is then applied with `μ_plus = min(μ.(x), 0.0)` etc. so that they can mess around with the function and it still have the upwind direction correct.

This should be in the main documentation examples

**Comment by chiyahn** [comment]
Sounds good. I'll get this done as priority asap -- that would help transition for HJBE notebook stuff as well
