### ISSUE TITLE
Try to build latex document and push with documentation using Tectonic

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/SimpleDifferentialOperators.jl#36]
Latex-specific component of #13

**Comment by jlperla** [comment]
`tectonic` is a build of latex that may make things much easier.  See https://malramsay.com/post/compiling_latex_on_travis/
  - Although we don't really need the `biber` thing which makes things harder than needed here.
  - Looks like we can put something like the following 
```
conda install -y -c conda-forge tectonic==0.1.8
```
- Or if we need to install conda
```
before_install:
  # Download and install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

    # Install tectonic
  - conda install -y -c conda-forge tectonic==0.1.8
```
  - Tectonic will cache all of the downloaded packages used for latex,
```
cache:
  directories:
    - $HOME/.cache/Tectonic
```
and maybe
```
cache:
  directories:
    - $HOME/.cache/Tectonic
    - $HOME/miniconda
```

**Comment by arnavs** [comment]
@jlperla I'm closing these issues now that we've moved away from the cloud-based latex/jupyter. But we can reopen if/when we revisit.
