### ISSUE TITLE
Docker or other alternative to building the latex

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#40]
As an alternative to #36  see some of the ideas in https://github.com/PHPirates/travis-ci-latex-pdf which meantions https://github.com/PHPirates/travis-ci-latex-pdf#tectonic-docker

and  https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci 

I think variations of this will use a docker within the CI.  As with the weave, we would want it to compile all of the `.jmd` files.

**Comment by arnavs** [comment]
https://github.com/JuliaDocs/DocumenterLaTeX.jl May be a good approach.

**Comment by jlperla** [comment]
It does have a docker image which could be used in the same way as we have discussed others 
 https://github.com/JuliaDocs/DocumenterLaTeX.jl/tree/master/docker  which is in https://hub.docker.com/r/juliadocs/documenter-latex/

Otherwise the backend is mostly there to hook into the PDF generation of actual documenter.jl output, so not sure how much other help it has.
