### ISSUE TITLE
Finalize build and docs

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#49]
- [x] Support "dev" as an option
- [x] Replace the links to the `.tex` with links to the relative PDF
- [x] Add in a new top level page at the level of installation and formulas with relative links to the notebooks built
- [x] See the behavior on dev after pushing docs and then a commit.

**Comment by arnavs** [comment]
Alright, we're set up here with the `dev` option (except I made it `./docs.sh master`, to match `./docs.sh {tag}`), relative links to PDF, and new page.

Two caveats: 

* Currently, I can only relative link files, and not the notebooks gallery. Not sure why. Currently I have it pointed it at `../generated/README.md`. One quick fix is to set a hard link in the markdown, but have the actual value be a Julia interpolated string. 

* `Documenter`'s commits overwrite ours, even with the default `forcepush = false`. I think a good answer is to set up a server to listen to pushes to `gh-pages` (or run as cron job), and run `./docs.sh master`.

**Comment by arnavs** [comment]
Sorry, to be clear- by "hard link in the markdown," I mean the `docs/src/notebooks.md`, and not the README thing I mentioned.

**Comment by jlperla** [comment]
Add in direct links to the notebook `.ipynb` and nbviewer as well.

**Comment by jlperla** [comment]
Default the docs link to `stable` on the front-page.   Maybe also have a `dev`.

**Comment by arnavs** [comment]
Genericizing the `nbgitviewer` link is not so easy (since the docs file is in pure Markdown, we'd have to inject a string replacement step somewhere...). 

For now, I just said: 

```
Click [here](https://nbviewer.jupyter.org/github/QuantEcon/SimpleDifferentialOperators.jl/tree/gh-pages/), and then select the appropriate version (`v0.2.1`, `dev`, etc.)
```

I'm closing as I don't think this is a showstopper (it might be a nice small project for someone who knows more than me about web stuff?). But if I'm wrong, let me know and I can work on it.
