### ISSUE TITLE
LCP notebook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#50]
Can add notes from https://github.com/econtoolkit/continuous_time_methods/blob/master/optimal_stopping.pdf

But ensure consistency with existing notation.

- [x] Find the cleanest, minimal version just with formulas (maybe using the PATH?) then put it in the docs example
- [x] Add in a simple version of two into the tests based on the simple one.
  - [x] One case with the drift upwind direction backward. 
  - [x] One where you need to split before of the different signs
  -  [x] Make sure you test with a 0 and a nonzero `S` value of stopping.

**Comment by arnavs** [comment]
@jlperla I checked in a first pass at this, see [here](https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/generated/LCP_simple.html).

**Comment by arnavs** [comment]
Also- do you have an example implementation of the split case (i.e., where we take the pos/neg parts of the vector depending on the drift). Just want to make sure I've got the signs and things right.

**Comment by arnavs** [comment]
Alright @jlperla added these tests, so all that's left on this is your signoff on the notebook (which you can reach from the `dev` docs).

**Comment by arnavs** [comment]
Uploaded a revised version of the notebook. This is without `PATH` output, which was mostly garbage, but I slacked you a copy of the output just in case. 

https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/generated/LCP_simple.html

**Comment by arnavs** [comment]
FYI, about the output, see https://github.com/chkwon/PATHSolver.jl/issues/34. So this is coming out of the base library, and there's nothing we can do at wrapper level. 

Will add the attributions manually, as you suggest.
