### ISSUE TITLE
Solve stationary KFE for diffusion process using the definition of the operators directly

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#51]
Solve as an eigenvalue problem and then renormalize properly

Should be in an example and a test.

**Comment by chiyahn** [comment]
+ convert HJBE example to use SDO package

**Comment by jlperla** [comment]
We can now put this stuff back as examples in https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Usage-1
- [ ] Add another example in the Usage section, as we had before, on a KFE example.
- [ ] First, do it directly by saying what the stationary ODE and the boundary conditions as differential equations/etc. are (i.e. don't need to explain that it is the adjoint or transposes).  For the symbol, call it `L_star` instead of `L` after you construct it.
- [ ] Then use the mixed boundary conditions to get the `0 = L_star p` setup
- [ ] Solve it as a sparse eigenvalue problem and then show how to normalize the solution.
- [ ] Next show that the backwards operator from the stochastic process we had before is `L` and show that the transpose of `L` is the same `L_star`.

**Comment by jlperla** [comment]
Don't forget to look at your old stuff to see what can be salvaged.  Lots, I imagine.
- https://github.com/ubcecon/computing_and_datascience/pull/99
- https://github.com/QuantEcon/SimpleDifferentialOperators.jl/issues/54
