### ISSUE TITLE
Docstring layout issues with unicode names

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#53]
If you take a look at https://quantecon.github.io/SimpleDifferentialOperators.jl/latest/api/#SimpleDifferentialOperators.ExtensionDifferentialOperator-Tuple{Any,DifferenceMethod}  and others, you will see it renders like 
![image](https://user-images.githubusercontent.com/13106721/53751437-1a917180-3e61-11e9-883a-0fbfe327fc9c.png)

Somehow the markdown escaping of these functions is incorrect... I think in the docstrings.  Are there ` when they are not needed by chance?

**Comment by arnavs** [comment]
It might be the spacing. Here's the docstring for the `v0.2.1` after I tidied it up (see e.g. [here](https://quantecon.github.io/SimpleDifferentialOperators.jl/v0.2/#Usage-1) for the render). 

It's important to pay attention to things like `, underscores, asterisks, etc. which have Markdown semantics. 

```
"""
   `diffusionoperators(x, BC1::BoundaryCondition, BC2::BoundaryCondition)`

Return the diffusion operators `(L_1_minus, L_1_plus, L_2)` w.r.t the supplied grid and BCs.

`x` is a grid (either an `AbstractRange`, in which we use specialized uniform grid code, or an `AbstractArray`). The
first BC binds at the lower end of the grid (i.e., `x[1]`), and the latter at the high end. The BCs are either a `Reflecting()`,
or "Dirichlet" boundary condition `v'(x) = 0`, or `Mixed(x::T) where {T <: Real}`, corresponding to "Robin" boundary conditions.
"""
diffusionoperators(x, BC1::BoundaryCondition, BC2::BoundaryCondition) = _diffusionoperators(x, BC1, BC2)
```

**Comment by arnavs** [comment]
Also, to check how the docs render locally, run `julia --project=docs/ docs/make.jl` from the repo level, and then open the HTML from `docs/build` in a browser.
