### ISSUE TITLE
Use the transpose to solve for the KFE in the notebook and the docs

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#54]
Then in #52 we reconstruct it using operators and boundary conditions.
- [x] Notebooks (Resolved by https://github.com/ubcecon/computing_and_datascience/pull/99)
- [x] Docs (Resolved by #63)

**Comment by chiyahn** [comment]
Notebook added in https://github.com/ubcecon/computing_and_datascience/pull/99 (without detailed docs); it can be found at https://github.com/ubcecon/computing_and_datascience/blob/master/continuous_time_methods/tutorials/kolmogorov-forward.md 

I'll work on the docs once #57 is done

**Comment by jlperla** [comment]
For the "docs", maybe put as an example at the end of https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Examples-1

**Comment by chiyahn** [comment]
@jlperla I found that I need to import an external package (like `NLsolve.jl`) to solve the system `Lx= 0`. Should I proceed though?

**Comment by jlperla** [comment]
Should be an e, igenvalue problem for the steady state distribution?

**Comment by chiyahn** [comment]
Yeah, I could use a package like `IterativeSolvers.jl` for it but I don't think you can solve eigenvalue problems using vanilla Julia. Also, for small state space these solvers are not good at finding nontrivial solutions either.

**Comment by jlperla** [comment]
I think the function is now in Arpack. It is `eigs` I think.

Am I missing something here? Just use the equivalent that maps to sparse eigenvalues in matlab

**Comment by chiyahn** [comment]
@jlperla It works. Turns out that I have been using the transpose of `\rho * I - \mu L_1 - \sigma^2 / 2 * L_2`, not `\mu L_1 + \sigma^2/2 * L_2`
