### ISSUE TITLE
Ensure the tex file is relatively complete 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#56]
i.e. we can replace https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf  with the tex file.

What would a new student want to see with the derivations

- [x] Use subscript for `-` and `+` for first order derivatives (Resolved in 4ce21ff)
- [x] Add a section for constructing operators with boundary conditions by stacking (Resolved in d83ae84)
- [x] Add a section for examples (Resolved in bb2a115)

**Comment by jlperla** [comment]
Show the simple non-controled bellmans with boundaries we use in the docs/code.

**Comment by chiyahn** [comment]
Added a few bullet points https://github.com/QuantEcon/SimpleDifferentialOperators.jl/issues/56#issue-416928712 for keeping track of the progress
