### ISSUE TITLE
Check that README.md is complete

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#60]
I have made some changes, but I would make sure that the whole thing makes sense and is sufficiently complete and clean.

**Comment by jlperla** [comment]
My basic thought is that our main "example" should be on the README as well.  Not everyone looks at docs.

**Comment by chiyahn** [comment]
@jlperla You mean the one with HJBE *AND* KFE?

**Comment by jlperla** [comment]
Dunno.  You can see how long it is.  Certainly the bellman that I wrote up is useful.  A few extra lines for the KFE couldn't hurt if it is short enough.
