### ISSUE TITLE
Review carefully check the LCP notebook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#65]
I made a bunch of changes to the LCP notebook.  There is some exposition on these sorts of problems, and I reorganized a lot of it.
- [x] Please go carefully through it, line by line, character by character, to make sure that there are no errors and that it looks slick.
- [x] Make sure that the layout is good in both HTML and jupyter (e.g. didn't make any code blocks too wide, etc.)
- [x] Check for spelling, etc.
- [x] Make sure equation numbers match
- [x] Make sure variable names match definitions, code, etc.

If it is solid, then initiate a notebook build and push to the docs.  I think we can tag tomorrow with this and push to quantecon as well.

**Comment by arnavs** [comment]
Will do.

**Comment by arnavs** [comment]
Ready for you @jlperla. I think the links from the documentation takes a while to sync, so it might be best to just navigate to the `gh-pages` branch and open directly in your browser.

Also, I couldn't get the math to display in browser using `jupyter lab` --- is this something that worked for you?

**Comment by arnavs** [comment]
@jlperla Updated my Weave, and the source to use the fence notation, and none of the math works in the notebook. These fences are the Julia Markdown math spec, and they're implemented for the HTML output.

I think the optimal course (as discussed) is to drop the download link for now, and file an issue/help request with Weave.

**Comment by jlperla** [comment]
Sounds good.  Just post the issue on Weave.jl to begin that discussion, and we can see what is involved.

**Comment by arnavs** [comment]
Perfect. In terms of reviewing the LCP, I'll push to the `gh-pages` branch in about 5 minutes, so navigating to it in your clone and opening it up in-browser is the best bet.

**Comment by jlperla** [comment]
OK.  Just tell me when to look

**Comment by arnavs** [comment]
Good now.

**Comment by jlperla** [comment]
https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/generated/LCP_simple.html Still has "Download notebook".

**Comment by arnavs** [comment]
Must have not pushed the commit, will do after lunch.

**Comment by arnavs** [comment]
@jlperla I'm closing as I figure you would've said something about the LCP notebook if it weren't OK? But can re-open if that's not the case.
