### ISSUE TITLE
Rearrange the sections of the notbook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#70]
@arnavs  I want us to do one more change to the structure of the docs, and then I think we should compile and tag everything.

Right now, the structure is still a little weird...  We don't want a usage example above the installation instructions, for example.  We want that as just the first example of usage.

Why not have the whole section called "Usage" or something like that, but not have any content at the top of it.  Then at the next level
- "Installation" as a subsection with the installation instructions in it
- "Usage Examples" as a subsection, as it is now, or just "Examples", with no direct content and just sub-examples (which could show up in the table of contents on the lhs of the notes, if you wish).
- What is currently at the top in the "Usage" above the installation would just move inside of the Usage Examples as the first example.  For the name, call it "Solving a Simple HJBE" or something like that.

Is that clear and does it make sense?

**Comment by arnavs** [comment]
Makes sense to me. @chiyahn let me know if you need any help with respect to things like configuring the sidebar/TOC.

**Comment by arnavs** [comment]
@chiyahn I think your last commit was slightly different than what was intended (i.e., "Installation" should be a subsection, etc.). Will reopen, but feel free to close if you subsequently agreed on something different.

**Comment by chiyahn** [comment]
Installation is in a subsection -- see discussion we had on Slack. I'll make a fix for 1.1 rn

**Comment by arnavs** [comment]
I've been trying to spend less time on Slack. To be clear, what was described was a subsection of the Usage umbrella, but this is fine as well.
