### ISSUE TITLE
Advanced LCP Notebook

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/SimpleDifferentialOperators.jl#72]
I checked one in (unlinked for now). You can find it in the `dev/` folder in the `gh-pages` branch. 

There's a regression in `MosekTools`, so unfortunately we can't demonstrate that solver until it's sorted out.

**Comment by arnavs** [comment]
@jlperla See: https://nbviewer.jupyter.org/github/QuantEcon/SimpleDifferentialOperators.jl/blob/gh-pages/dev/generated/LCP_advanced.ipynb

We can cut the last solver if it's too squiggly, but I thought it was nice to show what works, and what doesn't.

**Comment by jlperla** [comment]
Can't hurt to keep it in for now.  This is intended to be reasonably comprehensive.  But can you either use `@btime` or call the `time` twice?  Hard to get a sense of speed with the massive JuMP compilation timing.

**Comment by arnavs** [comment]
Sure, will switch to `@btime`.

**Comment by arnavs** [comment]
@jlperla Is it because of the negative drift that we have at least one negative eigenvalue? 

In the short run, this is preventing us from using `Mosek`, see https://github.com/JuliaOpt/MosekTools.jl/issues/2#issuecomment-471734866. But `Gurobi` was also complaining about the parameters. 

If that's the case, perhaps we could reformulate it that you want to stop when the value is too positive, or something.
