### ISSUE TITLE
Specialized Tridiagonal * Diagonal products

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#73]
See https://github.com/JuliaLang/julia/pull/28883 and all of the PRs/issues it references (also, perhaps https://github.com/JuliaLang/julia/issues/28994 is relevant, though not sure).

In particular, the ones that come up with this package frequently are:
- Diagonal * Tridiagonal
- Tridiagonal * Diagonal

With Julia 1.1 at least, you can see that Diagonal * Tridiagonal -> Sparse, which is a fallback we don't want.
```julia
julia> using LinearAlgebra

julia> A = Tridiagonal(rand(2), rand(3), rand(2))
3×3 Tridiagonal{Float64,Array{Float64,1}}:
 0.651845  0.692459   ⋅
 0.571598  0.955736  0.929357
  ⋅        0.460634  0.948893

julia> D = Diagonal(rand(3))
3×3 Diagonal{Float64,Array{Float64,1}}:
 0.235908   ⋅         ⋅
  ⋅        0.351151   ⋅
  ⋅         ⋅        0.242416

julia> A * D
3×3 SparseArrays.SparseMatrixCSC{Float64,Int64} with 7 stored entries:
  [1, 1]  =  0.153776
  [2, 1]  =  0.134845
  [1, 2]  =  0.243158
  [2, 2]  =  0.335608
  [3, 2]  =  0.161752
  [2, 3]  =  0.225291
  [3, 3]  =  0.230026
```
This should be efficiently done as a tridiagonal instead.

**Comment by mcognetta** [comment]
I have opened a PR to fix this: https://github.com/JuliaLang/julia/pull/31889

If there are any others of a similar flair, I would be happy to help with them.

**Comment by jlperla** [comment]
@mcognetta  Spectacular.  Thanks so much.

At this point, I am not aware of any others we have run into with this code.  But while you are in the zone, consider asking @dlfivefifty if there are any specialized operations on https://github.com/JuliaMatrices/BandedMatrices.jl that need implementation.
