### ISSUE TITLE
Notation cleanup prior to adding in absorbing barriers.

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#74]
Look at https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/generated/LCP_simple.html for examples  just to get consistency.

A few other notation things on the documentation first for consistency.  Looking at https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/
- [x] Make it clear in https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-constant-drifts-1 that this is solving the model for a reflecting barrier at `0.0` and `1.0`, and show the `\partial_x v(0) = 0` and `\partial_x v(1) = 0` in there.  Make the equations clear as well in https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-state-dependent-drifts-1 (Resolved by 579ccb8)
- [x] Add in the `L_x` consistently as an intermediate step.   I think that https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-state-dependent-drifts-1 is good for this, but the others are inconsistent. (Resolved by 4911376)
- [x] Get rid of `A` where we don't want them (Resolved by 4911376)
- [x] Don't call it `v_bc` or `v_interior` as it is just `v` (Resolved by aca2902)
- [x] Can use the unicode for `v_bar` to be consistent.
- [x] Add in a plot for https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Finding-stationary-distribution-from-the-Kolmogorov-forward-equation-(KFE)-1  ?  Consider adding in a simple plot of the value functions for the other examples as well. (Resolved by 1427ab5)
- [x] There are a few places with the hardcoded 0.05 instead of the rho to fix. (Resolved by 49c7650)
- [x] The extension approach has a few issues.  Maybe something closer to
```
using SparseArrays

L̄ₓ = μ*L̄₁₋(x) + σ^2 / 2 * L̄₂(x)

# boundary conditions (i.e. B v̄ = b)
B = [[-1; 1; zeros(M)] [zeros(M); -1; 1]]'
b =  [0.0; 0.0] 

# form bellman equation on extension
L̄ = [spzeros(3) ρ*I spzeros(3)] - L̄ₓ

# solve system of bellman and boundary condtions
v̄ =  [L̄; B] \ [f.(x); b]

v =  v̄[2:end-1] 
```
- [x] Note what I did there with the sparse zeros.  See if there are anywhere else you can use spzeros... (e.g. `[-1; 1; zeros(M)]` could be sparser) (Resolved by a09721e)
- [x] Get comments to follow the standard comment rules for spacing/etc.  https://github.com/QuantEcon/lecture-source-jl/blob/master/style.md#comment-spacing
- [x] Go to the README (https://github.com/QuantEcon/SimpleDifferentialOperators.jl/blob/master/README.md ) to make sure things are consistent there as well.

**Comment by chiyahn** [comment]
Loud and clear, will work on it after lunch
