### ISSUE TITLE
Reorg the documents so derivations are in a tex file and pdf within the repo

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#8]
- [x] This would have the current derivations, very pedantic in every step. (Resolved by c6b5ea9)
- [x] The current markdown would have the end results formula with the assumptions and code.  Pure usage.  Point to pdf for the derivation. (Resolved by b88d332)

**Comment by chiyahn** [comment]
Note that there are a few changes made in notebook:
https://github.com/ubcecon/computing_and_datascience/pull/97
which is currently WIP. I'll gradually add these to the dedicated repo https://github.com/QuantEcon/SimpleDifferentialOperators.jl/tree/master/docs/tex

**Comment by arnavs** [comment]
Perfect.
