### ISSUE TITLE
Make sure we use correct ranges in tutorials

### ISSUE THREAD

**Issue by chiyahn** [QuantEcon/SimpleDifferentialOperators.jl#83]
(After #84 is complete) Check if we are using the correct range for `x`, which should represent the interior rather than the ones that include boundary points.

```julia
x̄ = range(0.0, 1.0, length = 5)
x = x[2:(end-1)]
```
might be more appropriate, i.e., ghost nodes should correspond to the boundaries

**Comment by arnavs** [comment]
After you merge in the new docs, can you run `./docs.sh master` on your git Bash or *nix machine? That will repopulate the docs with generated notebooks and HTML.

**Comment by jlperla** [comment]
The only issue here is that the `x` there is an `AbstractArray` and hence cannot use the specializations of the functions for the generation of the operators.

I think the best approach may be if the operators are passed in the `x̄` rather than the `x` and we rethink a few things there.
