### ISSUE TITLE
Add functions for boundary extrapolation

### ISSUE THREAD

**Issue by chiyahn** [QuantEcon/SimpleDifferentialOperators.jl#85]
Implement a function `extrapolateboundary(v, x_bar, (BC1, BC2))` that returns `v_bar` on the extended grid given `x_bar` and `v` 

Progress tracker from https://github.com/QuantEcon/SimpleDifferentialOperators.jl/issues/85#issuecomment-476816329:

- [x] Add derivations in a separate appendix (Resolved by 2cf54d6)
- [x]  `(Mixed, Mixed)` implementation (Resolved by 1c1846d)
- [x] `(Reflecting, Reflecting)` implementation (Resolved by 1c1846d)
- [x] Unit tests for both (Resolved by 1c1846d)
- [x] Add in the docstring and jldoctest for them as well (Resolved by 1c1846d)
- [x] Use with the https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-constant-drifts-1 examples, etc. to plot the extrapolated version and v̄   i.e.  (Resolved by 7636fb3)

**Comment by jlperla** [comment]
Lets do this.  It is worthwhile for clarity of the code and algorithms (and a nontrivial function in some cases).

I think we should have the signature `extrapolatetoboundary(v, x_bar, (BC1, BC2))` where we do the necessary specializations for the BCs.
- [ ]  `(Mixed, Mixed)` implementation
- [ ] `(Reflecting, Reflecting)` implementation
- [ ] Unit tests for both
- [ ] Add in the docstring and jldoctest for them as well
- [ ] Use with the https://quantecon.github.io/SimpleDifferentialOperators.jl/dev/#Solving-HJBE-with-constant-drifts-1 examples, etc. to plot the extrapolated version and v̄   i.e. 
```
v̄ = extrapolatetoboundary(v, x̄, bc)
plot(x̄, v̄) # or whatever...
```

**Comment by chiyahn** [comment]
Formula for mixed boundary conditions:
$$
v(x_0) = \frac{1}{1-\underline{\xi} \Delta_{1,-} } v(x_1)
$$

$$
v(x_{M+1}) = \frac{1}{1+\overline{\xi} \Delta_{M,+} } v(x_M)
$$

for
$$
	\underline{\xi} v({x_{\min}}) + \partial_x v({x_{\min}} ) = 0 
$$
$$
	\overline{\xi} v({x_{\max}}) + \partial_x v({x_{\max}}) = 0
$$
where $x_{\min} = x_0$ and $x_{\max} = x_{M+1}$

**Comment by chiyahn** [comment]
First version:
```julia
"""
    extrapolate_to_boundary(v, x̄, bc::Tuple{Mixed, Mixed})

Returns a `length(x̄)`-vector whose `2:(length(x̄)-1)` elements are `v`,
the first and last element are extrapolated `v` on the boundaries of `x̄` according to
boundary conditions `bc` given.

The first element of `bc` is applied to the lower bound, and second element of `bc` to the upper.
# Examples
```jldoctest; setup = :(using SimpleDifferentialOperators)
julia> x̄ = 0:5
0:5

julia> x = x̄[2:length(x̄)]
1
2
3

julia> v = (x -> x^2).(x)
5-element Array{Int64,1}:
  1
  4
  9
 16
 25

julia> extrapolate_to_boundary(v, x̄, (Mixed(1), Mixed(1)))
7-element Array{Int64,1}:
  1
  1
  4
  9
 16
 25
 25
```
"""
function extrapolate_to_boundary(v, x̄, bc::Tuple{Mixed, Mixed})
    ξ_lb = bc[1].ξ
    ξ_ub = bc[2].ξ

    Δ_1_minus = diff(x̄)[1]
    Δ_M_plus = diff(x̄)[end]

    return [v[1]/(1-ξ_lb*Δ_1_minus); v; v[end]/(1+ξ_ub*Δ_M_plus)]
end

"""
    extrapolate_to_boundary(v, x̄, bc::Tuple{Reflecting, Reflecting})

Returns a `length(x̄)`-vector whose `2:(length(x̄)-1)` elements are `v`,
the first and last element are extrapolated `v` on the boundaries of `x̄` according to
boundary conditions `bc` given.

The first element of `bc` is applied to the lower bound, and second element of `bc` to the upper.
# Examples
```jldoctest; setup = :(using SimpleDifferentialOperators)
julia> x̄ = 0:5
0:5

julia> x = x̄[2:length(x̄)]
1
2
3

julia> v = (x -> x^2).(x)
5-element Array{Int64,1}:
  1
  4
  9
 16
 25

julia> extrapolate_to_boundary(v, x̄, (Reflecting(), Reflecting()))
7-element Array{Int64,1}:
  1
  1
  4
  9
 16
 25
 25
```
"""
function extrapolate_to_boundary(v, x̄, bc::Tuple{Reflecting, Reflecting})
    return [v[1]; v; v[end]]
end
```
not clear what would be the best way to do error handling for the case when denominators are zero. Also, it might worth adding derivation for extrapolation in appendix.

**Comment by jlperla** [comment]
For the example in ` extrapolate_to_boundary(v, x̄, bc::Tuple{Mixed, Mixed})` maybe pick something that doesn't end up with v[0] = v[1]

For the denominator of `0`, lets just not put in a special case for it at all.  It would have an Inf or a NaN or whatever the appropriate division is by.

Also, lets change the name to `extrapolatetoboundary` for naming consistency with the rest of julia and the package.

**Comment by jlperla** [comment]
This
```julia
Δ_1_minus = diff(x̄)[1]
Δ_M_plus = diff(x̄)[end]
```
is unnecessarily expensive.  It allocates an array even for uniform grids to get all the differences, and then finds the first and last ones from the allocated array.  Better to use multiple dispatch on this with
1. For `x̄::AbstractArray` use `x̄[2] - x̄[1]` and `x̄[end] - x̄[end-1]`
2. For `x̄::AbstractRange` use `step(x̄)`

> Also, it might worth adding derivation for extrapolation in appendix. 

I will add

**Comment by chiyahn** [comment]
Almost done, I'll wait for #126 to be done before I move on generating the plots based on `extrapolatetoboundary`.
