### ISSUE TITLE
Add tests for different data types

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#9]
Bigfloat.  Try with a dual number.

**Comment by jlperla** [comment]
This will be wrong: https://github.com/QuantEcon/SimpleDifferentialOperators.jl/blob/master/src/operators.jl#L21

`zeros` and `ones` should be related to the datatype of the range.

Need to

**Comment by arnavs** [comment]
@jlperla It works for `Dual`s! That is, with grids like `range(Dual(0.0), Dual(1.0), length = 100)`, and boundary condition objects like `Mixed(Dual(1.0))`.
