### ISSUE TITLE
`docs.sh` does not run on Windows machines

### ISSUE THREAD

**Issue by chiyahn** [QuantEcon/SimpleDifferentialOperators.jl#92]
Running `./docs.sh master` in git bash on my computer (Windows) returns the following messages:

```
Chiyoung Ahn@ARTS-ECON-AHN MINGW64 ~/.julia/dev/SimpleDifferentialOperators (master)
$ ./docs.sh master
No local changes to save
You selected the master branch.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
./docs.sh: line 26: julia: command not found
```

fyi my `./bash_profile` is
```
alias julia="C:/Users/Chiyoung\ Ahn/AppData/Local/Julia-1.1.0/bin/julia"
```

**Comment by arnavs** [comment]
Hey @chiyahn, thanks for the report. This is a more general setup problem. I think running bash scripts in Windows will always be clunky, but here is what I would recommend if you want to troubleshoot: 

1. Try replacing the `alias` with a genuine symbolic link. Something like `ln -s {julia_binary} /usr/bin/julia`. I'm not sure of the details on git bash, but would be happy to point you in the right direction. 

2. Make sure the Julia binary is in your Windows path (which you can access by typing "environment variables" into the search bar). 

Dunno. I'll probably just have this script run nightly on our new server anyway, so fixing this may be more trouble than it's worth.

**Comment by jlperla** [comment]
>  more trouble than it's worth.

Yup.  We need to get these things compiling automatically anyways.  @arnavs  before I forget, CY and I noticed that equation references were not updated correctly in the latex compiled document.  Is it possible that it is only running it once (i.e. yo need to run latex twice generally go get the aux file for equation references generated).

**Comment by arnavs** [comment]
Roger that, I'll add in a second `pdflatex` step. Thanks.

**Comment by arnavs** [comment]
I'll close this for now, then.
