### ISSUE TITLE
Rename interior to interiornodes and require passing in the boundary conditions

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#93]
I am concerned about two things here: (1) `interior` is the sort of function name that could end up clashing with all sorts of packages since Julia has weird namespace lookup rules and (2) that if we extend this to include multiple dimensions or thicker boundaries, we would need to have the boundary conditions to do the calculation.  So,
- [x] Change `interior(x̄)` to be `interiornodes(x̄, bc)`  where the `bc` is ignored for the current dispatch (but we might use it later) (Resolved by 8c4910c)
- [x] Change the unit tests (Resolved by 8c4910c)
- [x] Change the jldoctests (Resolved by 8c4910c)

**Comment by chiyahn** [comment]
Agreed. Will work on it
